version: '3'

volumes:
  postgres-data:
  redis-data:

networks:
  my_network:

services:
  db:
    image: postgres:14.8-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST: db
    networks:
      - my_network

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - my_network

  
  redis_pin_store:
    image: redis:7.2.4-alpine
    container_name: redis_pin_store
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - my_network

  greenlight:
    image: greenlight
    container_name: greenlight
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "587:587"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
    volumes:
      - ./app/javascript:/usr/src/app/app/javascript
      - ./log/cron.log:/var/log/cron.log
    networks:
      - my_network
